In [56]:
exec(open("../../Scripts/Packages.py").read())

Xvar = pd.read_csv("../../Data/Xvar.csv")
Yvar = pd.read_csv("../../Data/Yvar.csv")

,yearsPlayed,age,G_all,weight,G_dh,birthCountry - Japan,height,birthCountry - Cuba,birthCountry - D.R.,birthCountry - Venezuela,...,G_p,birthCountry - USA,NumPos,G_cf,G_rf,G_ss,G_2b,G_3b,G_c,G_lf
0,9.0,30.0,20.0,225.0,0.0,0,77.0,0,0,0,...,1.0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4.0,28.0,37.0,200.0,0.0,0,75.0,0,0,0,...,1.0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7.0,30.0,70.0,175.0,0.0,0,73.0,0,0,0,...,0.0,1,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,9.0,32.0,66.0,195.0,0.0,0,73.0,0,0,0,...,1.0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,10.0,31.0,96.0,192.0,0.0,0,71.0,0,0,0,...,0.0,1,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5,14.0,37.0,101.0,195.0,0.0,0,73.0,0,0,0,...,0.0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2.0,25.0,60.0,200.0,0.0,0,74.0,0,0,0,...,1.0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,14.0,33.0,46.0,200.0,0.0,0,75.0,0,0,0,...,1.0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,16.0,38.0,59.0,175.0,0.0,0,70.0,0,0,0,...,1.0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,5.0,30.0,138.0,195.0,0.0,0,76.0,0,0,0,...,0.0,1,2.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [58]:
samplesize = int(np.floor(Xvar.shape[0]/2))

train_sample = np.random.choice(Xvar.shape[0], replace=False, size=samplesize)
test_sample = np.random.choice(Xvar.loc[~Xvar.index.isin(train_sample)].shape[0], replace=False, size=samplesize)

X_train = Xvar.loc[train_sample]
Y_train = Yvar.loc[train_sample]
X_test = Xvar.loc[test_sample]

12787

In [59]:
# Linear Regression

logreg = LinearRegression()
logreg.fit(X_train, Y_train)
Y_pred = logreg.predict(X_test)
acc_log = round(logreg.score(X_train, Y_train) * 100, 2)
acc_log

27.809999999999999